import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import styles from "./categories.module.scss";

//components
import Layout from "../../components/Layout/layout";
import Share from "../../components/share/share";
import Thumbnail from "../../components/thumbnail/thumbnail";
import Loader from "../../components/loader/loader";

//firebase
import { fire } from "../../config/fire-config";
import { collection, onSnapshot, orderBy } from "firebase/firestore";

export default function Edition() {
  const [articles, setarticles] = useState([]);
  const [search, setSearch] = useState("");

  const router = useRouter();
  const { edition } = router.query;

  useEffect(() => {
    console.log(edition);
    onSnapshot(collection(fire, `${edition}`), (snapshot) => {
      setarticles(snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() })));
    });
  }, []);

  const autre = articles.filter((article) => article.position == "autre");
  const rubrique = articles.filter((article) => article.position == "rubrique");
  const alaune = articles.filter((article) => article.position == "alaune");
  const edito = articles.filter((article) => article.position == "edito");
  const prof = articles.filter((article) => article.position == "prof");
  const alumini = articles.filter((article) => article.position == "alumini");

  // const filterArticles = articles.filter((article) =>
  //   article.title.toLowerCase().includes(search.toLowerCase())
  // );

  return (
    <div>
      <Head>
        <title>MagEnsao || Archives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {articles.length == 0 ? (
        <Loader></Loader>
      ) : (
        <Layout>
          <div
            style={{
              display: "flex",
            }}
          >
            <div className={styles.pageContainer}>
              <div className={styles.title}>
                <h1>{edition}</h1>
              </div>
              <h3>Editorial</h3>
              <div className={styles.articles}>
                {edito.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
              </div>
              <h3>spécial</h3>
              <div className={styles.articles}>
                {rubrique.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
              </div>
              <h3>A la UNe</h3>
              <div className={styles.articles}>
                {alaune.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
              </div>
              <h3>ARTICLES DU MOIS</h3>
              <div className={styles.articles}>
                {autre.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
              </div>
              <h3>Professeur et alumini</h3>
              <div className={styles.articles}>
                {prof.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
                {alumini.map((article) => (
                  <Thumbnail key={article.id} {...article} margin></Thumbnail>
                ))}
              </div>
            </div>
          </div>
        </Layout>
      )}
    </div>
  );
}
