export const magdb = [
  {
    id: 8,
    thumbnail: "/magensao8.png",
    title: "MagEnsao N°8",
    date: "Mars, 2022",
    pdf: "https://tinyurl.com/magensao-8-pdf",
    read: " https://tinyurl.com/magensao-8-read",
  },
  {
    id: 7,
    thumbnail: "/magensao7.jpg",
    title: "MagEnsao N°7",
    date: "Février, 2022",
    pdf: "https://tinyurl.com/magensao-7-pdf",
    read: "https://tinyurl.com/magensao-7-read",
  },
  {
    id: 6,
    thumbnail: "/magensao6.jpg",
    title: "MagEnsao N°6",
    date: "Javnvier , 2022",
    pdf: "https://www.tinyurl.com/magensao-6-pdf",
    read: "https://tinyurl.com/magensao-6-read",
  },
  {
    id: 5,
    thumbnail: "/magensao5.png",
    title: "MagEnsao N°5",
    date: "Décembre , 2021",
    pdf: "https://www.tinyurl.com/magensao-5-pdf",
    read: "https://tinyurl.com/magensao-5-read",
  },
  {
    id: 4,
    thumbnail: "/magensao4.jpg",
    title: "MagEnsao N°4",
    date: "Novembre , 2021",
    pdf: "https://tinyurl.com/magensao-4-pdf",
    read: "https://tinyurl.com/magensao-4-read",
  },
  {
    id: 3,
    thumbnail: "/magensao3.png",
    title: "MagEnsao N°3",
    date: "Octobre , 2021",
    pdf: "https://tinyurl.com/magensao-3-pdf",
    read: "https://tinyurl.com/magensao-3-read",
  },
  {
    id: 2,
    thumbnail: "/magensao2.jpg",
    title: "MagEnsao N°2",
    date: "Juin , 2021",
    pdf: "https://drive.google.com/file/d/1iksCefYwet4U-2WLCXJE-7sj3hz63aOz/view?usp=sharing",
    read: "https://fr.calameo.com/read/0067401463e964ad19129",
  },
  {
    id: 1,
    thumbnail: "/magensao.jpeg",
    title: "MagEnsao N°1",
    date: "Avril , 2021",
    pdf: "https://drive.google.com/file/d/1MQgF-Y7sqZVYZUKhLiewziWHGzT_MG4m/view?usp=sharing",
    read: "https://fr.calameo.com/read/0067401467ce527d906f1",
  },
];
