import Head from "next/head";

//react
import react, { useState } from "react";
import { useForm } from "react-hook-form";

//styles
import styles from "../styles/admin.module.scss";

//firebase
import { fire, storage } from "../config/fire-config";
import { collection, addDoc } from "firebase/firestore";
import { getStorage, ref, uploadBytes, getDownloadURL } from "firebase/storage";

import Loader from "../components/loader/loader";

export default function Home() {
  const { register, handleSubmit, reset } = useForm();
  const [loader, setLoader] = useState(false);

  const onSubmit = (data) => {
    setLoader(true);
    console.log(loader);
    reset("");
    try {
      const storage = getStorage();
      const imgRef = ref(storage, data.img[0].name);
      uploadBytes(imgRef, data.img[0]).then((snapshot) => {
        console.log("Uploaded a blob or file!");
        getDownloadURL(imgRef).then(async (url) => {
          const docRef = await addDoc(collection(fire, "articles"), {
            ...data,
            img: url,
            createdAt: new Date().getTime(),
          });
        });
      });
    } catch (e) {
      console.error("Error adding document: ", e);
    }
    setLoader(false);
  };

  return (
    <div>
      <Head>
        <title>MagEnsao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.adminPage}>
        <div className={styles.logo}>
          <img src="/logo.png" width="35px"></img>
          <p>MagEnsao</p>
        </div>
        {loader ? (
          <Loader></Loader>
        ) : (
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className={styles.form}>
              <table>
                <tbody>
                  <tr>
                    <td>
                      <label>Titre :</label>
                    </td>
                    <td>
                      {" "}
                      <input
                        type="text"
                        placeholder="entrez le titre"
                        {...register("title", {
                          required: "Ce champ est obligatoire",
                        })}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <label>Écrit par :</label>
                    </td>
                    <td>
                      {" "}
                      <input
                        type="text"
                        placeholder="entrez l'auteur"
                        {...register("author", {
                          required: "Ce champ est obligatoire",
                        })}
                      ></input>
                    </td>
                  </tr>

                  <tr>
                    <td>
                      <label>Categorie :</label>
                    </td>
                    <td>
                      {" "}
                      <select
                        {...register("categorie", {
                          required: "Ce champ est obligatoire",
                        })}
                      >
                        <option value="coronavirus">coronavirus</option>
                        <option value="politique">politique</option>
                        <option value="economie">economie</option>
                        <option value="ingénierie">ingénierie</option>
                        <option value="culture">culture</option>
                        <option value="sport">sport</option>
                      </select>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <label>placer l'article :</label>
                    </td>
                    <td>
                      {" "}
                      <select
                        {...register("position", {
                          required: "Ce champ est obligatoire",
                        })}
                      >
                        <option value="slider">slider</option>
                        <option value="top">top articles</option>
                        <option value="essentiel">essentiel</option>
                        <option value="autre">autre</option>
                      </select>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <label>partie de l'article : </label>
                    </td>
                    <td>
                      {" "}
                      <input
                        type="text"
                        placeholder=" ..... s'il appartient au slider"
                        {...register("slug", {
                          required: "Ce champ est obligatoire",
                        })}
                      ></input>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <label>image de l'article :</label>
                    </td>
                    <td>
                      {" "}
                      <input
                        type="file"
                        placeholder="entrez l'image"
                        {...register("img", {
                          required: "Ce champ est obligatoire",
                        })}
                      ></input>
                    </td>
                  </tr>
                </tbody>
              </table>
              <div className={styles.textarea}>
                <label>l'Article :</label>
                <textarea
                  placeholder="article......"
                  {...register("article", {
                    required: "Ce champ est obligatoire",
                  })}
                ></textarea>
              </div>
            </div>
            <button type="submit"> Ajouter </button>
          </form>
        )}
      </div>
    </div>
  );
}
