import Head from "next/head";

//styles
import styles from "../styles/admin.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MagEnsao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.adminPage}>
        <div className={styles.logo}>
          <img src="/logo.png" width="35px"></img>
          <p>MagEnsao</p>
        </div>{" "}
        <form>
          <table>
            <tr>
              <td>
                <label>Titre :</label>
              </td>
              <td>
                {" "}
                <input
                  type="text"
                  placeholder="entrez le titre"
                  name="titre"
                ></input>
              </td>
            </tr>
            <tr>
              <td>
                <label>Écrit par :</label>
              </td>
              <td>
                {" "}
                <input type="text" placeholder="entrez l'auteur"></input>
              </td>
            </tr>
            <tr>
              <td>
                <label>Date :</label>
              </td>
              <td>
                {" "}
                <input type="date"></input>
              </td>
            </tr>
            <tr>
              <td>
                <label>Categorie :</label>
              </td>
              <td>
                {" "}
                <select name="categorie">
                  <option value="coronavirus">coronavirus</option>
                  <option value="politique">politique</option>
                  <option value="economie">economie</option>
                  <option value="ingénierie">ingénierie</option>
                </select>
              </td>
            </tr>
            <tr>
              <td>
                <label>placer l'article :</label>
              </td>
              <td>
                {" "}
                <select name="categorie">
                  <option value="slider">slider</option>
                  <option value="top">top articles</option>
                  <option value="essentiel">essentiel</option>
                  <option value="autre">autre</option>
                </select>
              </td>
            </tr>
            <tr>
              <td>
                <label>partie de l'article : </label>
              </td>
              <td>
                {" "}
                <input
                  type="text"
                  placeholder=" ..... s'il appartient au slider"
                  name="titre"
                ></input>
              </td>
            </tr>
          </table>
          <label>l'Article :</label>
          <textarea placeholder="article......"></textarea>
        </form>
      </div>
    </div>
  );
}
