import Head from "next/head";

import styles from "../styles/archive.module.scss";
import Link from "next/link";
//components
import Layout from "../components/Layout/layout";
import Share from "../components/share/share";
import Abonn from "../components/abonner/abonner";

//db
import { magdb } from "../db/mag";

export default function Archives() {
  return (
    <div>
      <Head>
        <title>MagEnsao || Archives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.archiveContainer}>
          <h2> nouvelles editions</h2>
          <div className={styles.editions}>
            <div className={styles.edition}>
              <Link href="/edition/avril2022">
                <p>Avril 2022</p>
              </Link>
            </div>

            <div className={styles.edition}>
              <Link href="/edition/juin2022">
                <p>Juin 2022</p>
              </Link>
            </div>
            <div className={styles.edition}>
              <Link href="/edition/octobre2022">
                <p>Octobre 2022</p>
              </Link>
            </div>
            <div className={styles.edition}>
              <Link href="/edition/decembre2022">
                <p>Decembre 2022</p>
              </Link>
            </div>

            <div className={styles.edition}>
              <Link href="/edition/janvier2023">
                <p>Janvier 2023</p>
              </Link>
            </div>
            <div className={styles.edition}>
              <Link href="/edition/fevrier2023">
                <p>Fevrier 2023</p>
              </Link>
            </div>
          </div>
          <h2>anciennes editons</h2>
          <div className={styles.magContainer}>
            {magdb.map((mag) => (
              <Link
                href={mag.read}
                target="_blank"
                rel="noreferrer"
                key={mag.id}
              >
                <div className={styles.mag}>
                  <div
                    className={styles.thumbnail}
                    style={{ backgroundImage: `url(${mag.thumbnail})` }}
                  ></div>
                </div>
                <div className={styles.links}>
                  <div className={styles.text}>
                    <h4>{mag.title}</h4>
                    <p>{mag.date}</p>
                  </div>
                  <Link
                    href={mag.read}
                    target="_blank"
                    rel="noreferrer"
                    style={{ marginTop: "15px" }}
                  >
                    <img
                      src="/readbook.png"
                      width="15px"
                      style={{ marginRight: "10px" }}
                    ></img>
                    Lecture interactive
                  </Link>
                  <Link
                    href={mag.pdf}
                    target="_blank"
                    rel="noreferrer"
                    style={{ marginTop: "10px" }}
                  >
                    <img
                      src="/download.png"
                      width="15px"
                      style={{ marginRight: "10px" }}
                    ></img>
                    PDF téléchargeable
                  </Link>
                </div>
              </Link>
            ))}
          </div>
        </div>
        <Abonn></Abonn>
      </Layout>
    </div>
  );
}
