import Head from "next/head";

import styles from "../styles/apropos.module.scss";

//components
import Layout from "../components/Layout/layout";
import Abonn from "../components/abonner/abonner";

export default function Archives() {
  return (
    <div>
      <Head>
        <title>MagEnsao || Chroniqueurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div
          className={styles.tree}
          style={{ display: "flex", flexWrap: "wrap", marginTop: "50px" }}
        >
          <div className={styles.profile}>
            <div
              className={styles.pdp}
              style={{ backgroundImage: "url(/malek.jpeg)" }}
            ></div>
            <div className={styles.name}>
              <h5>Abdel Malek El Hebil</h5>
              <p>Expert & Conférencier International</p>
            </div>
          </div>

          <div className={styles.profile}>
            <div
              className={styles.pdp}
              style={{ backgroundImage: "url(/seraj.jpeg)" }}
            ></div>
            <div className={styles.name}>
              <h5>Pr Khalid Serraj</h5>
              <p>Doyen de la Faculté de Médecine et de Pharmacie d’Oujda</p>
            </div>
          </div>
          <div className={styles.profile}>
            <div
              className={styles.pdp}
              style={{ backgroundImage: "url(/haddya.jpeg)" }}
            ></div>
            <div className={styles.name}>
              <h5>Pr Intissar Haddiya</h5>
              <p>Médecin néphrologue , Professeur de médecine et romancière</p>
            </div>
          </div>
          <div className={styles.profile}>
            <div
              className={styles.pdp}
              style={{ backgroundImage: "url(/foutassi.jpeg)" }}
            ></div>
            <div className={styles.name}>
              <h5>Pr. Maryam Fourtassi</h5>
              <p>faculte de medecine et de pharmacie oujda</p>
            </div>
          </div>
          <div className={styles.profile}>
            <div
              className={styles.pdp}
              style={{ backgroundImage: "url(/ouali.jpg)" }}
            ></div>
            <div className={styles.name}>
              <h5>Pr.Ouali Taoufik</h5>
              <p>Professeur physique quantique à université Mohammed Premier</p>
            </div>
          </div>
        </div>

        <Abonn></Abonn>
      </Layout>
    </div>
  );
}
