import Head from "next/head";

//styles
// import styles from "../styles/contact.module.scss";

//components
import Layout from "../components/Layout/layout";
import Share from "../components/share/share";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>MagEnsao || Archives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div style={{ display: "flex" }}>
          <Share></Share>
        </div>
      </Layout>
    </div>
  );
}
