import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

//components
import Layout from "../components/Layout/layout";
import Slider from "../components/slideshow/slider";
import Thumbnail from "../components/thumbnail/thumbnail";
import Abonner from "../components/abonner/abonner";
import Categorie from "../components/categorie/categorie";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MagEnsao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Slider></Slider>
        <div className={styles.topArticles}>
          <div className={styles.articles}>
            <h2 className={styles.title}>Articles du mois</h2>
            <div
              style={{
                display: "flex",
                flexWrap: "wrap",
                // alignItems: "center",
                justifyContent: "space-around",
              }}
            >
              <Thumbnail
                img="/machine.jpg"
                categorie="Ingénierie"
                titre=" Machine Learning – Définition, fonctionnement et secteurs d’application"
                date="Nov 03, 2021"
              ></Thumbnail>
              <Thumbnail
                img="/artisanat.jpg"
                categorie="Économie"
                titre="Artisanat : lancement du registre national pour la généralisation de l’AMO"
                date="Fév 22 , 2022"
              ></Thumbnail>
              <Thumbnail
                img="/politique.jpg"
                categorie="Politique"
                titre="Après les propos de l’influenceuse Mayssa, un proche de MHE assure qu’il n’est “plus du tout dans le jeu politique”"
                date="Fév 22 , 2022"
              ></Thumbnail>
              <Thumbnail
                img="/culture.jpg"
                categorie="culture"
                titre="“La poésie est invincible” : Abdellatif Laâbi, la poésie comme nature"
                date="Fév 18 , 2022"
              ></Thumbnail>
            </div>
          </div>
          <div className={styles.newsContainer}>
            <h2 className={styles.essentiel}>L’ESSENTIEL</h2>
            <div className={styles.news}>
              <p>
                Culture - <span>Fév 03 , 2022</span>
              </p>
              <h2>
                Ministère de l’Économie et des Finances : le pain à base de
                farine de blé tendre maintenu à son prix actuel
              </h2>
            </div>
            <div className={styles.news}>
              <p>
                Politique - <span>Fév 18 , 2022</span>
              </p>
              <h2>
                L’ancien vice-président américain Mike Pence attendu au Maroc et
                en Israël début mars
              </h2>
            </div>
            <div className={styles.news}>
              <p>
                Coronavirus - <span>Fév 07 , 2022</span>
              </p>
              <h2>
                Les frontières maritimes fermées jusqu’à nouvel ordre pour les
                passagers
              </h2>
            </div>
            <div className={styles.news}>
              <p>
                Sport - <span>Fév 22 , 2022</span>
              </p>
              <h2>
                Football : accord financier entre l’Ajax Amsterdam et la famille
                d’Abdelhak Nouri, victime d’un arrêt
              </h2>
            </div>
            <div className={styles.news}>
              <p>
                Économie - <span>Fév 22 , 2022</span>
              </p>
              <h2>
                HCP : l’Indice des prix à la consommation a augmenté de 3,1% en
                janvier 2022
              </h2>
            </div>
          </div>
        </div>

        <Abonner></Abonner>
        <Categorie categorie="Ingénierie"></Categorie>
        <Categorie categorie="Culture"></Categorie>
      </Layout>
    </div>
  );
}
