import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

//components
import Layout from "../components/Layout/layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MagEnsao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
    </div>
  );
}
